### ISSUE TITLE
Go module not compatible with 2.0.0

### ISSUE THREAD

**Issue by mholt** [silinternational/certmagic-storage-dynamodb#11]
Since tagging 2.0.0, `go get github.com/silinternational/certmagic-storage-dynamodb/v2` will not work because the `go.mod` file in this repo doesn't have the `/v2` suffix: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

(I also recommend using semantic version tags, starting with `v`)

For now the only way to use this package with Go modules is to use v1.

**Comment by fillup** [comment]
Thanks @mholt, I released `2.0.1` with that fix in place. Using the `v` in the version number actually isn't part of semver and is only sort of tolerated in tag names, but I'm a little particular and don't like them since they are redundant. https://semver.org/#is-v123-a-semantic-version

**Comment by mholt** [comment]
Good point; I always just took my cues from the Go wiki.
