### ISSUE TITLE
Fails when aws_region is not configured

### ISSUE THREAD

**Issue by danlsgiga** [silinternational/certmagic-storage-dynamodb#12]
Using the dynamodb storage for caddy v2.1.1, I'm getting the following error if I don't specify the `aws_region`.

```
obtaining certificate: failed storage check: MissingRegion: could not find region configuration - storage is probably misconfigured
```

Works fine if I have:

```
storage dynamodb <MYDYNAMOTABLE> {
  aws_region us-east-1
}
```

This should be an optional setting since the AWS Go SDK should populate the region from the instance metadata automatically.

**Comment by fillup** [comment]
Hi @danlsgiga, is it a problem for you to just grab it from the environment? I think the only requirement for that variable is as part of the Caddy module, but I haven't actually used that part yet myself so I wouldn't be comfortable removing it. 

@mholt, do you know if it would be a problem to not require the region as part of the Caddy module definition?

**Comment by mholt** [comment]
@fillup Good question, I'm not sure since I don't actually use DynamoDB (or AWS) myself 😅  I was under the impression that almost everything could be obtained from the environment on AWS.

As far as the Caddyfile and/or Caddy module goes, it doesn't matter either way (Caddy doesn't care).

**Comment by fillup** [comment]
Heh, okay well let's give it a shot without requiring it and we'll let @danlsgiga confirm for us. I'll update `develop` without it and see how that works.

**Comment by fillup** [comment]
@mholt is this the way to not require aws_region but still support it in the module? https://github.com/silinternational/certmagic-storage-dynamodb/commit/5140e535ec56fc78441d569716868893d43a1166

**Comment by danlsgiga** [comment]
> Hi @danlsgiga, is it a problem for you to just grab it from the environment? I think the only requirement for that variable is as part of the Caddy module, but I haven't actually used that part yet myself so I wouldn't be comfortable removing it.
> 
> @mholt, do you know if it would be a problem to not require the region as part of the Caddy module definition?

Hey @fillup, thanks for working on this.

So, AFAIK, the AWS Go SDK, by default, should pull the current region from the environment itself, unless you override it in the Session initialization... which I think you do [here](https://github.com/silinternational/certmagic-storage-dynamodb/blob/master/storage.go#L64-L74)

My suggestion is for you to check if the current region matches the provided one (if any) and if not, override the variable using https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/#EC2Metadata.RegionWithContext

**Comment by danlsgiga** [comment]
Actually... no! Please disregard my comment above... EC2Metadata would fail if you are running Caddy on anything but EC2, which is a very opinionated choice.

**Comment by danlsgiga** [comment]
It seems that I'm wrong and since I worked with the Route53 GO SDK before (which does not require a region) I was biased on thinking it would be true to everything else.

Sorry for the confusion. Closing this! Your code is working as expected, no further actions are required! ;)
