### ISSUE TITLE
Add the plugin to the Caddy download page

### ISSUE THREAD

**Issue by francislavoie** [silinternational/certmagic-storage-dynamodb#14]
Could you please sign up for an account here https://caddyserver.com/account and register your plugin so that it shows up on the list here https://caddyserver.com/download ?

This will advertise that the plugin is compatible with Caddy and make it available to add using the download page, and it will also automatically register this plugin's documentation here https://caddyserver.com/docs/json/storage/ along with the other supported storage plugins.

Thanks!

**Comment by fillup** [comment]
Sure, thanks for letting me know to do so!
https://caddyserver.com/docs/modules/caddy.storage.dynamodb
