### ISSUE TITLE
How to configure aws_endpoint and is it mandatory?

### ISSUE THREAD

**Issue by VelinGeorgiev** [silinternational/certmagic-storage-dynamodb#17]
I am looking at the docs [here ](https://caddyserver.com/docs/json/storage/dynamodb/)and trying to configure the module to work with Caddy, but I am confused regarding the param `aws_endpoint`. Is it mandatory or I can skip it since my IAM User has already permissions to dynamo db? Do you have an aws article I can look into so I can set it up. 

This is what I found but not sure if this is it: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-ddb.html
By the look of it the aws_endpoint is settings in json format.

Reference:

https://caddyserver.com/docs/json/storage/dynamodb/

```
{
	"module": "dynamodb",
	"table": "",
	"aws_endpoint": "",
	...
}
```

**Comment by fillup** [comment]
`aws_endpoint` is not required and is only present for local unit testing purposes. You can ignore it. I'll try to get the docs on the module page updated to reflect that.
