### ISSUE TITLE
Update listing to v3 on the Caddy website

### ISSUE THREAD

**Issue by mholt** [silinternational/certmagic-storage-dynamodb#27]
Hi, thanks for maintaining this module!

When you have a chance could you update the listing to v3 on the Caddy website? https://github.com/caddyserver/caddy/issues/5222#issuecomment-1328496668

Then it will work for people who download it :+1:

Cheers!

**Comment by Schparky** [comment]
> Hi, thanks for maintaining this module!
> 
> When you have a chance could you update the listing to v3 on the Caddy website? [caddyserver/caddy#5222 (comment)](https://github.com/caddyserver/caddy/issues/5222#issuecomment-1328496668)
> 
> Then it will work for people who download it +1
> 
> Cheers!

@mholt, thanks for bringing this to our attention. I am not the one that published the module and I have never done that. Could you give me a pointer on how to update the version on the Caddy website?

**Comment by mholt** [comment]
@Schparky Interesting, well, if you want to create an account at caddyserver.com, let me know and I'll transfer package ownership to your account. Then you can just update it there.

**Comment by Schparky** [comment]
> @Schparky Interesting, well, if you want to create an account at caddyserver.com, let me know and I'll transfer package ownership to your account. Then you can just update it there.

Created an account a few minutes ago. Added the package at v3, though it looks like there are two copies on https://caddyserver.com/docs/modules/ now.

**Comment by mholt** [comment]
@Schparky Awesome, thanks! I deleted the old one from the DB. It may take a while for the site to update its cache. (My backend is... not great, heh.)
