### ISSUE TITLE
xcaddy unable to download dependency: "github.com/aws/aws-sdk-go v1.44.185"

### ISSUE THREAD

**Issue by shmuelarditi** [silinternational/certmagic-storage-dynamodb#29]
as part of the multi-stage dockerfile we are using, the first part (builder) is using xcaddy to compile caddy with this plugin: github.com/silinternational/certmagic-storage-dynamodb/v3

Dockerfile:
`FROM caddy:builder AS builder `
`RUN xcaddy build --with github.com/silinternational/certmagic-storage-dynamodb/v3`

problem:  "go: downloading github.com/aws/aws-sdk-go v1.44.185" - loading forever i left it for 4 hours and it kept going..
for some reason xcaddy isnt able to download this specific version. 
![image](https://user-images.githubusercontent.com/91881199/218312879-771e6e69-8a3d-4a74-b800-636e2b9c859c.png)

earlier to that xcaddy did succeed in downloading : "github.com/aws/aws-sdk-go v1.43.26" (the version in the go.mod)
![image](https://user-images.githubusercontent.com/91881199/218313358-4df68501-c237-40eb-88ca-b30fd17053bb.png)

please let us know of a workaround or a fix to that.

**Comment by sgreer81** [comment]
It looks to be an issue with the 2.6.3 version of the caddy builder image. Pinning the builder image to 2.6.2 allows the build to succeed. Not a longer term solution, but a workaround for now.

Fails:
```
FROM caddy:builder AS builder
RUN xcaddy build --with github.com/silinternational/certmagic-storage-dynamodb/v3
```

Succeeds:
```
FROM caddy:2.6.2-builder AS builder
RUN xcaddy build --with github.com/silinternational/certmagic-storage-dynamodb/v3
```

**Comment by francislavoie** [comment]
See #30 for a workaround, and when merged, a fix.

**Comment by Schparky** [comment]
Fixed, thanks @francislavoie
